//API call 1 GET Method with diff Scenarios
GET http://localhost:3000/todos/?status=TO%20DO
###

//Scenario 2
GET http://localhost:3000/todos/?priority=HIGH
###

// Scenario 3
GET http://localhost:3000/todos/?priority=HIGH&status=IN%20PROGRESS
###

// Scenario 4
GET http://localhost:3000/todos/?search_q=Play
###


//API 2 GET Call by using id
GET http://localhost:3000/todos/8/
###

//API 3 POST Call 
POST http://localhost:3000/todos/
Content-Type: application/json

{
    "id": 10,
    "todo": "Finalize Event Time",
    "priority":"LOW",
    "status": "TO DO"
}
###

//API 4 PUT Method Call - Scenario 1
PUT http://localhost:3000/todos/8
Content-Type: application/json

{
    "status": "DONE"
}
###

//API 4 PUT Method Call - Scenario 2
PUT http://localhost:3000/todos/8
Content-Type: application/json

{
    "todo": "Some Task"
}
###

//API 4 PUT Method Call - Scenario 3
PUT http://localhost:3000/todos/8/
Content-Type: application/json

{
    "priority": "HIGH"
}
###

//API 5 DELETE Method 
DELETE http://localhost:3000/todos/10/
###